// Arabic is the reference dictionary: every other language file must provide
// exactly these keys (enforced via `satisfies` + the completeness test).
export const ar = {
  genericError: '❌ صار خطأ غير متوقع، حاول مرة ثانية.',
  notAdmin: '❌ هذا الأمر يحتاج صلاحية إدارة السيرفر أو الرول الإداري.',
  guildOnly: '❌ هذا الأمر يشتغل داخل سيرفر فقط.',
  // voice
  voiceDisabled: '⚠️ الميزات الصوتية معطلة في هذا السيرفر (/settings).',
  notInVoiceChannel: '❌ ادخل روم صوتي أول.',
  channelNotAllowed: '❌ هذا الروم مو مسموح للبوت (راجع /settings).',
  joinedVoice: '✅ دخلت الفويس وبدأت الاستماع 🎙️ (قل "{wake}" وبعدها أمرك)',
  leftVoice: '👋 طلعت من الفويس.',
  notConnected: '❌ البوت مو موجود في الفويس. استخدم /join',
  listenQuotaExhausted: '⏳ خلصت دقائق الاستماع اليومية لهذا السيرفر. نرجع بكرة!',
  aiQuotaExhausted: '⏳ خلصت أسئلة الذكاء الاصطناعي اليومية لهذا السيرفر.',
  ttsFailed: '❌ فشل تحويل النص إلى صوت.',
  aiFailed: '😅 ما قدرت أجاوب حالياً، جرب بعد شوي.',
  voiceHelp: 'الأوامر: اطلع، اسكت، السرعة، اطرد + اسم، قل + نص، أو اسألني أي شيء.',
  kickNeedsAdmin: '❌ طرد الأعضاء بالصوت يحتاج صلاحية إدارة السيرفر أو الرول الإداري.',
  kickNoMatch: '❓ ما قدرت أحدد مين تقصد، وضّح الاسم أكثر.',
  kickFailed: 'ما قدرت أطرد العضو، تأكد من صلاحياتي.',
  // settings
  settingsSaved: '✅ انحفظ الإعداد.',
  settingsTitle: '⚙️ إعدادات السيرفر',
  settingsFieldVoice: '🎙️ الصوتي',
  settingsFieldProtectionWelcome: '🛡️ الحماية والترحيب',
  settingsFieldQuotas: '⏳ الحصص اليومية',
  settingsQuotasLine: 'استماع: {listen} دقيقة • أسئلة AI: {ai}',
  labelEnabled: 'مفعل',
  labelWakeWord: 'كلمة التنبيه',
  labelDialect: 'اللهجة',
  labelPersonality: 'الشخصية الكوميدية',
  labelProtection: 'الحماية',
  labelWelcome: 'الترحيب',
  labelLanguage: 'لغة البوت',
  yes: 'نعم',
  no: 'لا',
  on: 'مفعّل',
  off: 'معطّل',
  dialectGulf: 'خليجية',
  dialectSyrian: 'سورية',
  dialectEgyptian: 'مصرية',
  dialectMsa: 'فصحى',
  // welcome preview
  welcomeEnabledNote: '✅ الترحيب مفعّل.',
  welcomeDisabledNote: '⚠️ الترحيب معطّل حالياً — فعّله من لوحة التحكم أو /settings.',
  welcomeChannelNote: '📢 قناة الترحيب: {channel}',
  welcomeNoChannelNote: '⚠️ ما تم تحديد قناة ترحيب بعد — اخترها من لوحة التحكم.',
  welcomeChannelMissing: '🚨 قناة الترحيب المحددة غير موجودة أو ليست قناة نصية — اخترها من جديد.',
  welcomeChannelNoSend: '🚨 البوت لا يملك صلاحية إرسال الرسائل في قناة الترحيب — لن تصل أي رسالة ترحيب!',
  welcomeChannelNoAttach: '⚠️ البوت لا يملك صلاحية إرفاق الملفات في قناة الترحيب — سيصل النص بدون صورة الترحيب.',
  // welcome/farewell defaults ('' in config = use these)
  defaultWelcome: 'أهلاً {user} في {server}! 🎮',
  defaultFarewell: 'وداعاً {user} 👋',
  unknownMember: '؟',
  // text protection — localized reason labels (raw enum tokens like "word"
  // inside RTL text trigger bidi reordering and read as jumbled)
  reasonWord: 'كلمة محظورة',
  reasonScam: 'احتيال/سكام',
  reasonInvite: 'رابط دعوة خارجي',
  reasonShortener: 'رابط مختصر',
  textDeleted: '{user} رسالتك حُذفت ({reason}). ممنوع الروابط المشبوهة/السكام.',
  textDeletedTimeout: '{user} رسالتك حُذفت ({reason}) وتم إسكاتك مؤقتاً {minutes} دقيقة بسبب التكرار.',
  textLogDeleted: '🛡️ حذف رسالة من {user} في {channel} — السبب: {reason}',
  textLogTimeoutSuffix: ' — ⏳ إسكات {minutes} دقيقة (مخالفة رقم {strike})',
  // voice moderation
  voiceWarnNotice: '⚠️ تحذير {user}: انتبه لألفاظك. تكرار الألفاظ غير اللائقة سيؤدي إلى إخراجك من الصوت.',
  voiceKickedNotice: '🚫 تم إخراج {user} من الصوت بسبب ألفاظ غير لائقة.',
  voiceKickFailedNotice: '⚠️ رصدت ألفاظاً من {user} لكن تعذّر إخراجه — تأكد أن رتبة البوت أعلى من رتبته ولديه صلاحية «نقل الأعضاء».',
  // weekly summary
  summaryTitle: '📊 **ملخص الأسبوع — {server}**',
  summaryTotals: '💬 الرسائل: **{messages}** • 🎙️ دقائق الصوت: **{voiceMinutes}**',
  summaryTopHeader: 'الأكثر نشاطاً هذا الأسبوع:',
  summaryTopLine: '{medal} {user} — {messages} رسالة، {voiceMinutes} دقيقة صوت',
  // reaction roles (self-assign)
  rolesPanelPosted: '✅ تم نشر لوحة الرتب.',
  rolesNotConfigured: '⚠️ لوحة الرتب غير مفعّلة أو ما فيها أزرار — أعدّها من لوحة التحكم.',
  roleAdded: '✅ أعطيتك رتبة {role}.',
  roleRemoved: '✅ شلت عنك رتبة {role}.',
  roleToggleFailed: '❌ ما قدرت أغيّر الرتبة — تأكد أن رتبة البوت أعلى ولديه صلاحية «إدارة الرتب».',
} as const;
