// Arabic is the reference dictionary: every other language file must provide
// exactly these keys (enforced via `satisfies` + the completeness test).
export const ar = {
  genericError: '❌ صار خطأ غير متوقع، حاول مرة ثانية.',
  notAdmin: '❌ هذا الأمر يحتاج صلاحية إدارة السيرفر أو الرول الإداري.',
  guildOnly: '❌ هذا الأمر يشتغل داخل سيرفر فقط.',
  // voice
  voiceDisabled: '⚠️ الميزات الصوتية معطلة في هذا السيرفر (/settings).',
  notInVoiceChannel: '❌ ادخل روم صوتي أول.',
  channelNotAllowed: '❌ هذا الروم مو مسموح للبوت (راجع /settings).',
  joinedVoice: '✅ دخلت الفويس وبدأت الاستماع 🎙️ (قل "{wake}" وبعدها أمرك)',
  voiceJoinFailed: '❌ ما قدرت أدخل القناة الصوتية.',
  leftVoice: '👋 طلعت من الفويس.',
  notConnected: '❌ البوت مو موجود في الفويس. استخدم /join',
  listenQuotaExhausted: '⏳ خلصت دقائق الاستماع اليومية لهذا السيرفر. نرجع بكرة!',
  aiQuotaExhausted: '⏳ خلصت أسئلة الذكاء الاصطناعي اليومية لهذا السيرفر.',
  ttsFailed: '❌ فشل تحويل النص إلى صوت.',
  aiFailed: '😅 ما قدرت أجاوب حالياً، جرب بعد شوي.',
  wakeAck: 'نعم؟ تفضّل، أنا أسمعك.',
  voiceHelp: 'الأوامر: اطلع، اسكت، السرعة، اطرد + اسم، قل + نص، أو اسألني أي شيء.',
  kickNeedsAdmin: '❌ طرد الأعضاء بالصوت يحتاج صلاحية إدارة السيرفر أو الرول الإداري.',
  kickNoMatch: '❓ ما قدرت أحدد مين تقصد، وضّح الاسم أكثر.',
  kickFailed: 'ما قدرت أطرد العضو، تأكد من صلاحياتي.',
  commandNotAllowed: '❌ هذا الأمر غير مسموح لك.',
  slashDisabled: '❌ هذا الأمر معطّل في هذا السيرفر.',
  dmFailed: 'تعذّر إرسال الرسالة الخاصة (قد تكون الخاصات مقفلة).',
  dmInactiveStarted: 'بدأت إرسال رسائل خاصة لـ {count} عضو غائب.',
  dmBulkStarted: 'إرسال الرسالة الخاصة إلى {count} عضو.',
  spamDmNotice: '🧹 تم حذف رسائلك المتكررة في سيرفر {server} — إرسال الرسالة نفسها في عدة قنوات يُعد سباماً.',
  spamLogDeleted: '🧹 سبام: حُذفت رسالة مكررة من {user} أُرسلت في {count} قنوات.',
  // settings
  settingsSaved: '✅ انحفظ الإعداد.',
  settingsTitle: '⚙️ إعدادات السيرفر',
  settingsFieldVoice: '🎙️ الصوتي',
  settingsFieldProtectionWelcome: '🛡️ الحماية والترحيب',
  settingsFieldQuotas: '⏳ الحصص اليومية',
  settingsQuotasLine: 'استماع: {listen} دقيقة • أسئلة AI: {ai}',
  labelEnabled: 'مفعل',
  labelWakeWord: 'كلمة التنبيه',
  labelPersonality: 'الشخصية الكوميدية',
  labelProtection: 'الحماية',
  labelWelcome: 'الترحيب',
  labelLanguage: 'لغة البوت',
  yes: 'نعم',
  no: 'لا',
  on: 'مفعّل',
  off: 'معطّل',
  // welcome preview
  welcomeEnabledNote: '✅ الترحيب مفعّل.',
  welcomeDisabledNote: '⚠️ الترحيب معطّل حالياً — فعّله من لوحة التحكم أو /settings.',
  welcomeChannelNote: '📢 قناة الترحيب: {channel}',
  welcomeNoChannelNote: '⚠️ ما تم تحديد قناة ترحيب بعد — اخترها من لوحة التحكم.',
  welcomeChannelMissing: '🚨 قناة الترحيب المحددة غير موجودة أو ليست قناة نصية — اخترها من جديد.',
  welcomeChannelNoSend: '🚨 البوت لا يملك صلاحية إرسال الرسائل في قناة الترحيب — لن تصل أي رسالة ترحيب!',
  welcomeChannelNoAttach: '⚠️ البوت لا يملك صلاحية إرفاق الملفات في قناة الترحيب — سيصل النص بدون صورة الترحيب.',
  // welcome/farewell defaults ('' in config = use these)
  defaultWelcome: 'أهلاً {user} في {server}! 🎮',
  defaultFarewell: 'وداعاً {user} 👋',
  unknownMember: '؟',
  // text protection — localized reason labels (raw enum tokens like "word"
  // inside RTL text trigger bidi reordering and read as jumbled)
  reasonWord: 'كلمة محظورة',
  reasonScam: 'احتيال/سكام',
  reasonInvite: 'رابط دعوة خارجي',
  reasonShortener: 'رابط مختصر',
  reasonDomain: 'رابط ممنوع',
  textDeleted: '{user} رسالتك حُذفت ({reason}). ممنوع الروابط المشبوهة/السكام.',
  textDeletedTimeout: '{user} رسالتك حُذفت ({reason}) وتم إسكاتك مؤقتاً {minutes} دقيقة بسبب التكرار.',
  textLogDeleted: '🛡️ حذف رسالة من {user} في {channel} — السبب: {reason}',
  textLogTimeoutSuffix: ' — ⏳ إسكات {minutes} دقيقة (مخالفة رقم {strike})',
  // voice moderation
  voiceWarnNotice: '⚠️ تحذير {user}: انتبه لألفاظك. تكرار الألفاظ غير اللائقة سيؤدي إلى إخراجك من الصوت.',
  voiceKickedNotice: '🚫 تم إخراج {user} من الصوت بسبب ألفاظ غير لائقة.',
  voiceKickFailedNotice: '⚠️ رصدت ألفاظاً من {user} لكن تعذّر إخراجه — تأكد أن رتبة البوت أعلى من رتبته ولديه صلاحية «نقل الأعضاء».',
  // weekly summary
  summaryTitle: '📊 **ملخص الأسبوع — {server}**',
  summaryTotals: '💬 الرسائل: **{messages}** • 🎙️ دقائق الصوت: **{voiceMinutes}**',
  summaryTopHeader: 'الأكثر نشاطاً هذا الأسبوع:',
  summaryTopLine: '{medal} {user} — {messages} رسالة، {voiceMinutes} دقيقة صوت',
  // AI channel summary (catch me up)
  summaryEmpty: 'ما فيه رسائل كافية ألخصها في هذه القناة.',
  summaryHeader: '📝 **ملخص آخر الرسائل:**',
  // voice command responses (routed by bot language)
  voiceLeft: 'طلعت من الفويس.',
  voiceStopped: 'وقفت الاستماع وسكّرت سماعتي 🎧 — استخدم /listen عشان أرجع أسمع.',
  voiceResumed: 'رجعت أسمع 🎙️ — قل "{wake}" وبعدها أمرك.',
  voicePing: 'سرعة الاتصال {ms} ملي ثانية.',
  voiceKicked: 'طردت {name} من الفويس.',
  // spoken moderation lines (TTS, routed by bot language like all replies)
  voiceWarnSpoken: 'يا {name}، انتبه لألفاظك، هذا تحذير. التكرار سيؤدي إلى إخراجك.',
  voiceKickedSpoken: 'يا {name}، تم إخراجك بسبب الألفاظ غير اللائقة.',
} as const;
