import type { ar } from './ar.js';

export const de = {
  genericError: '❌ Etwas ist schiefgelaufen, bitte versuch es erneut.',
  notAdmin: '❌ Dieser Befehl erfordert die Berechtigung „Server verwalten" oder die Admin-Rolle.',
  guildOnly: '❌ Dieser Befehl funktioniert nur innerhalb eines Servers.',
  voiceDisabled: '⚠️ Die Sprachfunktionen sind auf diesem Server deaktiviert (/settings).',
  notInVoiceChannel: '❌ Tritt zuerst einem Sprachkanal bei.',
  channelNotAllowed: '❌ Dieser Kanal ist für den Bot nicht freigegeben (siehe /settings).',
  joinedVoice: '✅ Sprachkanal betreten, ich höre zu 🎙️ (sag „{wake}" und dann deinen Befehl)',
  leftVoice: '👋 Sprachkanal verlassen.',
  notConnected: '❌ Der Bot ist in keinem Sprachkanal. Nutze /join',
  listenQuotaExhausted: '⏳ Die täglichen Zuhör-Minuten dieses Servers sind aufgebraucht. Bis morgen!',
  aiQuotaExhausted: '⏳ Die täglichen KI-Fragen dieses Servers sind aufgebraucht.',
  ttsFailed: '❌ Sprachausgabe fehlgeschlagen.',
  aiFailed: '😅 Ich kann gerade nicht antworten, versuch es gleich nochmal.',
  voiceHelp: 'Befehle: raus, leise, Tempo, kick + Name, sag + Text, oder frag mich irgendwas.',
  kickNeedsAdmin: '❌ Mitglieder per Stimme zu kicken erfordert „Server verwalten" oder die Admin-Rolle.',
  kickNoMatch: '❓ Ich konnte nicht erkennen, wen du meinst — sag den Namen deutlicher.',
  kickFailed: 'Konnte das Mitglied nicht entfernen, prüfe meine Berechtigungen.',
  settingsSaved: '✅ Einstellung gespeichert.',
  settingsTitle: '⚙️ Server-Einstellungen',
  settingsFieldVoice: '🎙️ Sprache',
  settingsFieldProtectionWelcome: '🛡️ Schutz & Willkommen',
  settingsFieldQuotas: '⏳ Tageslimits',
  settingsQuotasLine: 'Zuhören: {listen} Min. • KI-Fragen: {ai}',
  labelEnabled: 'Aktiviert',
  labelWakeWord: 'Aktivierungswort',
  labelDialect: 'Dialekt',
  labelPersonality: 'Komödiantische Persönlichkeit',
  labelProtection: 'Schutz',
  labelWelcome: 'Willkommen',
  labelLanguage: 'Bot-Sprache',
  yes: 'ja',
  no: 'nein',
  on: 'an',
  off: 'aus',
  dialectGulf: 'Golf-Arabisch',
  dialectSyrian: 'Syrisch',
  dialectEgyptian: 'Ägyptisch',
  dialectMsa: 'Hocharabisch',
  welcomeEnabledNote: '✅ Willkommensnachrichten sind aktiviert.',
  welcomeDisabledNote: '⚠️ Willkommensnachrichten sind derzeit deaktiviert — aktiviere sie im Dashboard oder per /settings.',
  welcomeChannelNote: '📢 Willkommenskanal: {channel}',
  welcomeNoChannelNote: '⚠️ Noch kein Willkommenskanal gewählt — wähle einen im Dashboard.',
  welcomeChannelMissing: '🚨 Der eingestellte Willkommenskanal existiert nicht mehr oder ist kein Textkanal — wähle einen neuen.',
  welcomeChannelNoSend: '🚨 Der Bot darf im Willkommenskanal keine Nachrichten senden — es kommen keine Willkommensnachrichten an!',
  welcomeChannelNoAttach: '⚠️ Der Bot darf im Willkommenskanal keine Dateien anhängen — der Text kommt ohne Willkommensbild an.',
  defaultWelcome: 'Willkommen {user} auf {server}! 🎮',
  defaultFarewell: 'Tschüss {user} 👋',
  unknownMember: '?',
  reasonWord: 'gesperrtes Wort',
  reasonScam: 'Scam',
  reasonInvite: 'fremder Einladungslink',
  reasonShortener: 'Link-Kürzer',
  textDeleted: '{user} deine Nachricht wurde gelöscht ({reason}). Verdächtige Links/Scams sind verboten.',
  textDeletedTimeout: '{user} deine Nachricht wurde gelöscht ({reason}) und du wurdest wegen Wiederholung für {minutes} Min. stummgeschaltet.',
  textLogDeleted: '🛡️ Nachricht von {user} in {channel} gelöscht — Grund: {reason}',
  textLogTimeoutSuffix: ' — ⏳ Timeout {minutes} Min. (Verstoß Nr. {strike})',
  voiceWarnNotice: '⚠️ Warnung {user}: Achte auf deine Sprache. Bei Wiederholung wirst du aus dem Sprachkanal entfernt.',
  voiceKickedNotice: '🚫 {user} wurde wegen unangemessener Sprache aus dem Sprachkanal entfernt.',
  voiceKickFailedNotice: '⚠️ Unangemessene Sprache von {user} erkannt, konnte aber nicht entfernen — die Bot-Rolle muss über der des Mitglieds stehen und „Mitglieder verschieben" braucht es auch.',
  summaryTitle: '📊 **Wochenrückblick — {server}**',
  summaryTotals: '💬 Nachrichten: **{messages}** • 🎙️ Sprachminuten: **{voiceMinutes}**',
  summaryTopHeader: 'Am aktivsten diese Woche:',
  summaryTopLine: '{medal} {user} — {messages} Nachrichten, {voiceMinutes} Sprachminuten',
} as const satisfies Record<keyof typeof ar, string>;
