import type { ar } from './ar.js';

export const de = {
  genericError: '❌ Etwas ist schiefgelaufen, bitte versuch es erneut.',
  notAdmin: '❌ Dieser Befehl erfordert die Berechtigung „Server verwalten" oder die Admin-Rolle.',
  guildOnly: '❌ Dieser Befehl funktioniert nur innerhalb eines Servers.',
  voiceDisabled: '⚠️ Die Sprachfunktionen sind auf diesem Server deaktiviert (/settings).',
  voicePremiumRequired: '💎 Der Sprachassistent ist Premium-Servern vorbehalten — upgrade dein Konto und verknüpfe diesen Server im Dashboard.',
  notInVoiceChannel: '❌ Tritt zuerst einem Sprachkanal bei.',
  channelNotAllowed: '❌ Dieser Kanal ist für den Bot nicht freigegeben (siehe /settings).',
  joinedVoice: '✅ Sprachkanal betreten, ich höre zu 🎙️ (sag „{wake}" und dann deinen Befehl)',
  voiceJoinFailed: '❌ Konnte dem Sprachkanal nicht beitreten.',
  leftVoice: '👋 Sprachkanal verlassen.',
  notConnected: '❌ Der Bot ist in keinem Sprachkanal. Nutze /join',
  listenQuotaExhausted: '⏳ Die monatlichen Zuhör-Minuten dieses Servers sind aufgebraucht. Sie erneuern sich zum Monatsbeginn!',
  aiQuotaExhausted: '⏳ Die monatlichen KI-Fragen dieses Servers sind aufgebraucht.',
  ttsFailed: '❌ Sprachausgabe fehlgeschlagen.',
  aiFailed: '😅 Ich kann gerade nicht antworten, versuch es gleich nochmal.',
  wakeAck: 'Ja? Ich höre — sag deinen Befehl.',
  voiceHelp: 'Befehle: raus, leise, Tempo, kick + Name, sag + Text, oder frag mich irgendwas.',
  kickNeedsAdmin: '❌ Mitglieder per Stimme zu kicken erfordert „Server verwalten" oder die Admin-Rolle.',
  kickNoMatch: '❓ Ich konnte nicht erkennen, wen du meinst — sag den Namen deutlicher.',
  kickFailed: 'Konnte das Mitglied nicht entfernen, prüfe meine Berechtigungen.',
  commandNotAllowed: '❌ Du darfst diesen Befehl nicht verwenden.',
  slashDisabled: '❌ Dieser Befehl ist auf diesem Server deaktiviert.',
  dmFailed: 'DM konnte nicht gesendet werden (DMs evtl. geschlossen).',
  dmInactiveStarted: 'Sende DMs an {count} inaktive Mitglieder.',
  dmBulkStarted: 'Sende die DM an {count} Mitglieder.',
  spamDmNotice: '🧹 Deine wiederholten Nachrichten in {server} wurden entfernt — dieselbe Nachricht in mehreren Kanälen zu posten gilt als Spam.',
  spamLogDeleted: '🧹 Spam: Nachricht von {user} in {count} Kanälen entfernt.',
  settingsSaved: '✅ Einstellung gespeichert.',
  settingsTitle: '⚙️ Server-Einstellungen',
  settingsFieldVoice: '🎙️ Sprache',
  settingsFieldProtectionWelcome: '🛡️ Schutz & Willkommen',
  settingsFieldQuotas: '⏳ Monatslimits',
  settingsQuotasLine: 'Zuhören: {listen} Min./Monat • KI-Fragen: {ai}/Monat',
  labelEnabled: 'Aktiviert',
  labelWakeWord: 'Aktivierungswort',
  labelPersonality: 'Komödiantische Persönlichkeit',
  labelProtection: 'Schutz',
  labelWelcome: 'Willkommen',
  labelLanguage: 'Bot-Sprache',
  yes: 'ja',
  no: 'nein',
  on: 'an',
  off: 'aus',
  welcomeEnabledNote: '✅ Willkommensnachrichten sind aktiviert.',
  welcomeDisabledNote: '⚠️ Willkommensnachrichten sind derzeit deaktiviert — aktiviere sie im Dashboard oder per /settings.',
  welcomeChannelNote: '📢 Willkommenskanal: {channel}',
  welcomeNoChannelNote: '⚠️ Noch kein Willkommenskanal gewählt — wähle einen im Dashboard.',
  welcomeChannelMissing: '🚨 Der eingestellte Willkommenskanal existiert nicht mehr oder ist kein Textkanal — wähle einen neuen.',
  welcomeChannelNoSend: '🚨 Der Bot darf im Willkommenskanal keine Nachrichten senden — es kommen keine Willkommensnachrichten an!',
  welcomeChannelNoAttach: '⚠️ Der Bot darf im Willkommenskanal keine Dateien anhängen — der Text kommt ohne Willkommensbild an.',
  defaultWelcome: 'Willkommen {user} auf {server}! 🎮',
  defaultFarewell: 'Tschüss {user} 👋',
  unknownMember: '?',
  reasonWord: 'gesperrtes Wort',
  reasonScam: 'Scam',
  reasonInvite: 'fremder Einladungslink',
  reasonShortener: 'Link-Kürzer',
  reasonDomain: 'gesperrter Link',
  textDeleted: '{user} deine Nachricht wurde gelöscht ({reason}). Verdächtige Links/Scams sind verboten.',
  textDeletedTimeout: '{user} deine Nachricht wurde gelöscht ({reason}) und du wurdest wegen Wiederholung für {minutes} Min. stummgeschaltet.',
  textLogDeleted: '🛡️ Nachricht von {user} in {channel} gelöscht — Grund: {reason}',
  textLogTimeoutSuffix: ' — ⏳ Timeout {minutes} Min. (Verstoß Nr. {strike})',
  voiceWarnNotice: '⚠️ Warnung {user}: Achte auf deine Sprache. Bei Wiederholung wirst du aus dem Sprachkanal entfernt.',
  voiceKickedNotice: '🚫 {user} wurde wegen unangemessener Sprache aus dem Sprachkanal entfernt.',
  voiceKickFailedNotice: '⚠️ Unangemessene Sprache von {user} erkannt, konnte aber nicht entfernen — die Bot-Rolle muss über der des Mitglieds stehen und „Mitglieder verschieben" braucht es auch.',
  summaryTitle: '📊 **Wochenrückblick — {server}**',
  summaryTotals: '💬 Nachrichten: **{messages}** • 🎙️ Sprachminuten: **{voiceMinutes}**',
  summaryTopHeader: 'Am aktivsten diese Woche:',
  summaryTopLine: '{medal} {user} — {messages} Nachrichten, {voiceMinutes} Sprachminuten',
  // AI channel summary (catch me up)
  summaryEmpty: 'Nicht genug Nachrichten zum Zusammenfassen in diesem Channel.',
  summaryHeader: '📝 **Zusammenfassung der letzten Nachrichten:**',
  // voice command responses (routed by bot language)
  voiceLeft: 'Habe den Voice-Channel verlassen.',
  voiceStopped: 'Höre nicht mehr zu und habe mich taub gestellt 🎧 — /listen zum Fortsetzen.',
  voiceResumed: 'Ich höre wieder zu 🎙️ — sag "{wake}" und dann deinen Befehl.',
  voicePing: 'Die Latenz beträgt {ms} ms.',
  voiceKicked: '{name} aus dem Voice entfernt.',
  voiceWarnSpoken: 'Hey {name}, achte auf deine Ausdrucksweise — das ist eine Verwarnung. Bei Wiederholung wirst du entfernt.',
  voiceKickedSpoken: '{name}, du wurdest wegen unangemessener Ausdrucksweise aus dem Voice entfernt.',
  distributeNotEnough: '❌ Nicht genug Mitglieder zum Verteilen (mindestens 2).',
  distributeNoChannels: '❌ Keine Kanäle mit dem angegebenen Namen gefunden.',
  distributeDone: '✅ {count} Mitglieder in Kanäle verteilt.',
  ticketAlreadyOpen: '⚠️ Du hast bereits ein offenes Ticket.',
  ticketNoCategory: '❌ Keine Kategorie für Tickets in den Einstellungen festgelegt.',
  ticketCreateFailed: '❌ Ticket konnte nicht erstellt werden.',
  ticketCreated: '✅ Dein Ticket wurde in {channel} erstellt.',
  ticketWelcomeDefault: 'Willkommen {mention}! 👋\nBeschreibe dein Anliegen und wir helfen dir.',
  ticketCloseFailed: '❌ Ticket konnte nicht geschlossen werden.',
  ticketClosedDefault: 'Ticket geschlossen. Vielen Dank für deine Nachricht!',
  ticketLogClosed: '🔒 Ticket geschlossen',
  ticketClaimDenied: '❌ Du hast keine Berechtigung, dieses Ticket zu übernehmen.',
  ticketClaimed: '👋 {user} hat dieses Ticket übernommen.',
} as const satisfies Record<keyof typeof ar, string>;
