import type { ar } from './ar.js';

export const en = {
  genericError: '❌ Something went wrong, please try again.',
  notAdmin: '❌ This command requires Manage Server permission or the admin role.',
  guildOnly: '❌ This command only works inside a server.',
  voiceDisabled: '⚠️ Voice features are disabled in this server (/settings).',
  notInVoiceChannel: '❌ Join a voice channel first.',
  channelNotAllowed: '❌ This channel is not allowed for the bot (see /settings).',
  joinedVoice: '✅ Joined voice and started listening 🎙️ (say "{wake}" followed by your command)',
  leftVoice: '👋 Left the voice channel.',
  notConnected: '❌ The bot is not in a voice channel. Use /join',
  listenQuotaExhausted: "⏳ Today's voice-listening minutes for this server are used up. Back tomorrow!",
  aiQuotaExhausted: "⏳ Today's AI questions for this server are used up.",
  ttsFailed: '❌ Text-to-speech failed.',
  aiFailed: "😅 Couldn't answer right now, try again in a bit.",
  wakeAck: "Yes? I'm listening — go ahead.",
  voiceHelp: 'Commands: leave, quiet, speed, kick + name, say + text, or ask me anything.',
  kickNeedsAdmin: '❌ Voice-kicking members requires Manage Server permission or the admin role.',
  kickNoMatch: "❓ Couldn't tell who you mean, please be more specific.",
  kickFailed: "Couldn't kick the member, check my permissions.",
  commandNotAllowed: '❌ You are not allowed to use this command.',
  slashDisabled: '❌ This command is disabled in this server.',
  dmFailed: "Couldn't send the DM (their DMs may be closed).",
  dmInactiveStarted: 'Sending DMs to {count} inactive members.',
  dmBulkStarted: 'Sending the DM to {count} members.',
  spamDmNotice: '🧹 Your repeated messages in {server} were removed — posting the same message in several channels counts as spam.',
  spamLogDeleted: '🧹 Spam: removed a message from {user} posted across {count} channels.',
  settingsSaved: '✅ Setting saved.',
  settingsTitle: '⚙️ Server settings',
  settingsFieldVoice: '🎙️ Voice',
  settingsFieldProtectionWelcome: '🛡️ Protection & welcome',
  settingsFieldQuotas: '⏳ Daily quotas',
  settingsQuotasLine: 'Listening: {listen} min • AI questions: {ai}',
  labelEnabled: 'Enabled',
  labelWakeWord: 'Wake word',
  labelPersonality: 'Comedic personality',
  labelProtection: 'Protection',
  labelWelcome: 'Welcome',
  labelLanguage: 'Bot language',
  yes: 'yes',
  no: 'no',
  on: 'on',
  off: 'off',
  welcomeEnabledNote: '✅ Welcome messages are enabled.',
  welcomeDisabledNote: '⚠️ Welcome messages are currently disabled — enable them in the dashboard or /settings.',
  welcomeChannelNote: '📢 Welcome channel: {channel}',
  welcomeNoChannelNote: '⚠️ No welcome channel selected yet — pick one in the dashboard.',
  welcomeChannelMissing: '🚨 The configured welcome channel no longer exists or is not a text channel — pick a new one.',
  welcomeChannelNoSend: '🚨 The bot cannot send messages in the welcome channel — no welcome messages will arrive!',
  welcomeChannelNoAttach: '⚠️ The bot cannot attach files in the welcome channel — the text will arrive without the welcome image.',
  defaultWelcome: 'Welcome {user} to {server}! 🎮',
  defaultFarewell: 'Goodbye {user} 👋',
  unknownMember: '?',
  reasonWord: 'blocked word',
  reasonScam: 'scam',
  reasonInvite: 'foreign invite link',
  reasonShortener: 'link shortener',
  reasonDomain: 'blocked link',
  textDeleted: '{user} your message was deleted ({reason}). Suspicious links/scams are not allowed.',
  textDeletedTimeout: '{user} your message was deleted ({reason}) and you were timed out for {minutes} min for repeating it.',
  textLogDeleted: '🛡️ Deleted a message from {user} in {channel} — reason: {reason}',
  textLogTimeoutSuffix: ' — ⏳ timeout {minutes} min (strike #{strike})',
  voiceWarnNotice: '⚠️ Warning {user}: watch your language. Repeating inappropriate language will get you removed from voice.',
  voiceKickedNotice: '🚫 {user} was removed from voice for inappropriate language.',
  voiceKickFailedNotice: "⚠️ Detected inappropriate language from {user} but couldn't remove them — make sure the bot's role is above theirs and it has the Move Members permission.",
  summaryTitle: '📊 **Weekly recap — {server}**',
  summaryTotals: '💬 Messages: **{messages}** • 🎙️ Voice minutes: **{voiceMinutes}**',
  summaryTopHeader: 'Most active this week:',
  summaryTopLine: '{medal} {user} — {messages} messages, {voiceMinutes} voice minutes',
  // AI channel summary (catch me up)
  summaryEmpty: 'Not enough messages to summarize in this channel.',
  summaryHeader: '📝 **Summary of recent messages:**',
  // voice command responses (routed by bot language)
  voiceLeft: 'Left the voice channel.',
  voiceStopped: 'Stopped listening and deafened myself 🎧 — use /listen to resume.',
  voiceResumed: 'Listening again 🎙️ — say "{wake}" followed by your command.',
  voicePing: 'Latency is {ms} ms.',
  voiceKicked: 'Kicked {name} from voice.',
  // spoken moderation lines (TTS, routed by bot language like all replies)
  voiceWarnSpoken: 'Hey {name}, watch your language — this is a warning. Repeating it will get you removed.',
  voiceKickedSpoken: '{name}, you were removed from voice for inappropriate language.',
} as const satisfies Record<keyof typeof ar, string>;
