import type { ar } from './ar.js';

export const fr = {
  genericError: '❌ Une erreur inattendue est survenue, réessaie.',
  notAdmin: '❌ Cette commande nécessite la permission Gérer le serveur ou le rôle admin.',
  guildOnly: '❌ Cette commande ne fonctionne que dans un serveur.',
  voiceDisabled: '⚠️ Les fonctions vocales sont désactivées sur ce serveur (/settings).',
  notInVoiceChannel: "❌ Rejoins d'abord un salon vocal.",
  channelNotAllowed: "❌ Ce salon n'est pas autorisé pour le bot (voir /settings).",
  joinedVoice: '✅ Salon vocal rejoint, j\'écoute 🎙️ (dis « {wake} » puis ta commande)',
  leftVoice: '👋 J\'ai quitté le salon vocal.',
  notConnected: "❌ Le bot n'est pas dans un salon vocal. Utilise /join",
  listenQuotaExhausted: "⏳ Les minutes d'écoute quotidiennes de ce serveur sont épuisées. À demain !",
  aiQuotaExhausted: '⏳ Les questions IA quotidiennes de ce serveur sont épuisées.',
  ttsFailed: '❌ La synthèse vocale a échoué.',
  aiFailed: '😅 Je ne peux pas répondre pour le moment, réessaie dans un instant.',
  wakeAck: "Oui ? Je t'écoute — vas-y.",
  voiceHelp: 'Commandes : sors, silence, vitesse, expulse + nom, dis + texte, ou pose-moi une question.',
  kickNeedsAdmin: '❌ Expulser des membres à la voix nécessite Gérer le serveur ou le rôle admin.',
  kickNoMatch: "❓ Je n'ai pas compris de qui tu parles, précise le nom.",
  kickFailed: "Impossible d'expulser le membre, vérifie mes permissions.",
  commandNotAllowed: "❌ Tu n'as pas le droit d'utiliser cette commande.",
  slashDisabled: '❌ Cette commande est désactivée sur ce serveur.',
  dmFailed: "Impossible d'envoyer le MP (ses MP sont peut-être fermés).",
  dmInactiveStarted: 'Envoi de MP à {count} membres inactifs.',
  spamDmNotice: '🧹 Tes messages répétés sur {server} ont été supprimés — poster le même message dans plusieurs salons est considéré comme du spam.',
  spamLogDeleted: '🧹 Spam : message de {user} supprimé dans {count} salons.',
  settingsSaved: '✅ Paramètre enregistré.',
  settingsTitle: '⚙️ Paramètres du serveur',
  settingsFieldVoice: '🎙️ Vocal',
  settingsFieldProtectionWelcome: '🛡️ Protection et bienvenue',
  settingsFieldQuotas: '⏳ Quotas quotidiens',
  settingsQuotasLine: 'Écoute : {listen} min • Questions IA : {ai}',
  labelEnabled: 'Activé',
  labelWakeWord: 'Mot d\'activation',
  labelPersonality: 'Personnalité comique',
  labelProtection: 'Protection',
  labelWelcome: 'Bienvenue',
  labelLanguage: 'Langue du bot',
  yes: 'oui',
  no: 'non',
  on: 'activé',
  off: 'désactivé',
  welcomeEnabledNote: '✅ Les messages de bienvenue sont activés.',
  welcomeDisabledNote: '⚠️ Les messages de bienvenue sont désactivés — active-les dans le tableau de bord ou /settings.',
  welcomeChannelNote: '📢 Salon de bienvenue : {channel}',
  welcomeNoChannelNote: '⚠️ Aucun salon de bienvenue choisi — sélectionne-en un dans le tableau de bord.',
  welcomeChannelMissing: "🚨 Le salon de bienvenue configuré n'existe plus ou n'est pas un salon texte — choisis-en un autre.",
  welcomeChannelNoSend: '🚨 Le bot ne peut pas envoyer de messages dans le salon de bienvenue — aucun message de bienvenue ne partira !',
  welcomeChannelNoAttach: "⚠️ Le bot ne peut pas joindre de fichiers dans le salon de bienvenue — le texte arrivera sans l'image de bienvenue.",
  defaultWelcome: 'Bienvenue {user} sur {server} ! 🎮',
  defaultFarewell: 'Au revoir {user} 👋',
  unknownMember: '?',
  reasonWord: 'mot bloqué',
  reasonScam: 'arnaque',
  reasonInvite: "lien d'invitation externe",
  reasonShortener: 'raccourcisseur de lien',
  reasonDomain: 'lien interdit',
  textDeleted: '{user} ton message a été supprimé ({reason}). Les liens suspects/arnaques sont interdits.',
  textDeletedTimeout: '{user} ton message a été supprimé ({reason}) et tu es réduit au silence {minutes} min pour récidive.',
  textLogDeleted: '🛡️ Message de {user} supprimé dans {channel} — raison : {reason}',
  textLogTimeoutSuffix: ' — ⏳ silence {minutes} min (infraction n°{strike})',
  voiceWarnNotice: '⚠️ Avertissement {user} : surveille ton langage. En cas de récidive, tu seras retiré du vocal.',
  voiceKickedNotice: '🚫 {user} a été retiré du vocal pour propos inappropriés.',
  voiceKickFailedNotice: "⚠️ Propos inappropriés détectés chez {user} mais impossible de le retirer — vérifie que le rôle du bot est au-dessus du sien et qu'il a la permission Déplacer des membres.",
  summaryTitle: '📊 **Récap de la semaine — {server}**',
  summaryTotals: '💬 Messages : **{messages}** • 🎙️ Minutes vocales : **{voiceMinutes}**',
  summaryTopHeader: 'Les plus actifs cette semaine :',
  summaryTopLine: '{medal} {user} — {messages} messages, {voiceMinutes} minutes vocales',
  // AI channel summary (catch me up)
  summaryEmpty: 'Pas assez de messages à résumer dans ce salon.',
  summaryHeader: '📝 **Résumé des messages récents :**',
  // voice command responses (routed by bot language)
  voiceLeft: "J'ai quitté le salon vocal.",
  voiceStopped: "J'ai arrêté d'écouter et je me suis rendu sourd 🎧 — /listen pour reprendre.",
  voiceResumed: "J'écoute à nouveau 🎙️ — dis « {wake} » puis ta commande.",
  voicePing: 'La latence est de {ms} ms.',
  voiceKicked: '{name} expulsé du vocal.',
  voiceWarnSpoken: "Hé {name}, surveille ton langage — c'est un avertissement. Si tu recommences, tu seras retiré.",
  voiceKickedSpoken: '{name}, tu as été retiré du vocal pour langage inapproprié.',
} as const satisfies Record<keyof typeof ar, string>;
