import type { ar } from './ar.js';

export const ru = {
  genericError: '❌ Произошла непредвиденная ошибка, попробуй ещё раз.',
  notAdmin: '❌ Эта команда требует права «Управлять сервером» или админ-роль.',
  guildOnly: '❌ Эта команда работает только внутри сервера.',
  voiceDisabled: '⚠️ Голосовые функции на этом сервере отключены (/settings).',
  notInVoiceChannel: '❌ Сначала зайди в голосовой канал.',
  channelNotAllowed: '❌ Этот канал не разрешён для бота (см. /settings).',
  joinedVoice: '✅ Зашёл в голосовой канал и слушаю 🎙️ (скажи «{wake}», а затем свою команду)',
  leftVoice: '👋 Вышел из голосового канала.',
  notConnected: '❌ Бот не в голосовом канале. Используй /join',
  listenQuotaExhausted: '⏳ Дневные минуты прослушивания для этого сервера закончились. Вернёмся завтра!',
  aiQuotaExhausted: '⏳ Дневные ИИ-вопросы для этого сервера закончились.',
  ttsFailed: '❌ Не удалось озвучить текст.',
  aiFailed: '😅 Сейчас не могу ответить, попробуй чуть позже.',
  wakeAck: 'Да? Я слушаю — говори.',
  voiceHelp: 'Команды: выйди, тише, скорость, кикни + имя, скажи + текст, или спроси меня о чём угодно.',
  kickNeedsAdmin: '❌ Кик участников голосом требует права «Управлять сервером» или админ-роль.',
  kickNoMatch: '❓ Не понял, кого ты имеешь в виду — назови имя точнее.',
  kickFailed: 'Не смог кикнуть участника, проверь мои права.',
  commandNotAllowed: '❌ Тебе нельзя использовать эту команду.',
  slashDisabled: '❌ Эта команда отключена на этом сервере.',
  dmFailed: 'Не удалось отправить ЛС (возможно, ЛС закрыты).',
  dmInactiveStarted: 'Отправляю ЛС {count} неактивным участникам.',
  spamDmNotice: '🧹 Твои повторяющиеся сообщения на сервере {server} удалены — одно и то же сообщение в нескольких каналах считается спамом.',
  spamLogDeleted: '🧹 Спам: сообщение от {user} удалено из {count} каналов.',
  settingsSaved: '✅ Настройка сохранена.',
  settingsTitle: '⚙️ Настройки сервера',
  settingsFieldVoice: '🎙️ Голос',
  settingsFieldProtectionWelcome: '🛡️ Защита и приветствия',
  settingsFieldQuotas: '⏳ Дневные лимиты',
  settingsQuotasLine: 'Прослушивание: {listen} мин • ИИ-вопросы: {ai}',
  labelEnabled: 'Включено',
  labelWakeWord: 'Слово-активатор',
  labelPersonality: 'Комичный характер',
  labelProtection: 'Защита',
  labelWelcome: 'Приветствие',
  labelLanguage: 'Язык бота',
  yes: 'да',
  no: 'нет',
  on: 'вкл',
  off: 'выкл',
  welcomeEnabledNote: '✅ Приветственные сообщения включены.',
  welcomeDisabledNote: '⚠️ Приветственные сообщения сейчас отключены — включи их в панели или через /settings.',
  welcomeChannelNote: '📢 Канал приветствий: {channel}',
  welcomeNoChannelNote: '⚠️ Канал приветствий ещё не выбран — выбери его в панели.',
  welcomeChannelMissing: '🚨 Настроенный канал приветствий больше не существует или не является текстовым — выбери новый.',
  welcomeChannelNoSend: '🚨 У бота нет права отправлять сообщения в канале приветствий — приветствия не будут доходить!',
  welcomeChannelNoAttach: '⚠️ У бота нет права прикреплять файлы в канале приветствий — текст придёт без приветственной картинки.',
  defaultWelcome: 'Добро пожаловать, {user}, на {server}! 🎮',
  defaultFarewell: 'Пока, {user} 👋',
  unknownMember: '?',
  reasonWord: 'запрещённое слово',
  reasonScam: 'скам',
  reasonInvite: 'сторонняя ссылка-приглашение',
  reasonShortener: 'сокращатель ссылок',
  reasonDomain: 'запрещённая ссылка',
  textDeleted: '{user} твоё сообщение удалено ({reason}). Подозрительные ссылки/скам запрещены.',
  textDeletedTimeout: '{user} твоё сообщение удалено ({reason}), и за повтор ты получил таймаут на {minutes} мин.',
  textLogDeleted: '🛡️ Удалено сообщение от {user} в {channel} — причина: {reason}',
  textLogTimeoutSuffix: ' — ⏳ таймаут {minutes} мин (нарушение №{strike})',
  voiceWarnNotice: '⚠️ Предупреждение {user}: следи за словами. При повторе будешь удалён из голосового канала.',
  voiceKickedNotice: '🚫 {user} удалён из голосового канала за недопустимые выражения.',
  voiceKickFailedNotice: '⚠️ Обнаружены недопустимые выражения от {user}, но удалить не удалось — роль бота должна быть выше, и нужно право «Перемещать участников».',
  summaryTitle: '📊 **Итоги недели — {server}**',
  summaryTotals: '💬 Сообщения: **{messages}** • 🎙️ Голосовые минуты: **{voiceMinutes}**',
  summaryTopHeader: 'Самые активные за неделю:',
  summaryTopLine: '{medal} {user} — {messages} сообщений, {voiceMinutes} минут в голосе',
  // AI channel summary (catch me up)
  summaryEmpty: 'В этом канале недостаточно сообщений для сводки.',
  summaryHeader: '📝 **Сводка последних сообщений:**',
  // voice command responses (routed by bot language)
  voiceLeft: 'Вышел из голосового канала.',
  voiceStopped: 'Перестал слушать и заглушил себя 🎧 — /listen, чтобы продолжить.',
  voiceResumed: 'Снова слушаю 🎙️ — скажи «{wake}» и команду.',
  voicePing: 'Задержка {ms} мс.',
  voiceKicked: '{name} исключён из войса.',
  voiceWarnSpoken: 'Эй {name}, следи за словами — это предупреждение. Повторишь — будешь удалён.',
  voiceKickedSpoken: '{name}, ты был удалён из войса за неподобающие выражения.',
} as const satisfies Record<keyof typeof ar, string>;
