import type { ar } from './ar.js';

export const tr = {
  genericError: '❌ Beklenmedik bir hata oluştu, lütfen tekrar dene.',
  notAdmin: '❌ Bu komut Sunucuyu Yönet izni veya yönetici rolü gerektirir.',
  guildOnly: '❌ Bu komut yalnızca bir sunucu içinde çalışır.',
  voiceDisabled: '⚠️ Bu sunucuda ses özellikleri devre dışı (/settings).',
  notInVoiceChannel: '❌ Önce bir ses kanalına gir.',
  channelNotAllowed: '❌ Bu kanal bot için izinli değil (bkz. /settings).',
  joinedVoice: '✅ Ses kanalına girdim ve dinlemeye başladım 🎙️ ("{wake}" de, ardından komutunu söyle)',
  leftVoice: '👋 Ses kanalından çıktım.',
  notConnected: '❌ Bot bir ses kanalında değil. /join kullan',
  listenQuotaExhausted: '⏳ Bu sunucunun günlük dinleme dakikaları bitti. Yarın görüşürüz!',
  aiQuotaExhausted: '⏳ Bu sunucunun günlük yapay zekâ soruları bitti.',
  ttsFailed: '❌ Metin okuma başarısız oldu.',
  aiFailed: '😅 Şu an yanıt veremiyorum, birazdan tekrar dene.',
  voiceHelp: 'Komutlar: çık, sus, hız, at + isim, söyle + metin, ya da bana bir şey sor.',
  kickNeedsAdmin: '❌ Sesle üye atmak Sunucuyu Yönet izni veya yönetici rolü gerektirir.',
  kickNoMatch: '❓ Kimi kastettiğini anlayamadım, ismi daha net söyle.',
  kickFailed: 'Üyeyi atamadım, izinlerimi kontrol et.',
  commandNotAllowed: '❌ Bu komutu kullanma iznin yok.',
  settingsSaved: '✅ Ayar kaydedildi.',
  settingsTitle: '⚙️ Sunucu ayarları',
  settingsFieldVoice: '🎙️ Ses',
  settingsFieldProtectionWelcome: '🛡️ Koruma ve karşılama',
  settingsFieldQuotas: '⏳ Günlük kotalar',
  settingsQuotasLine: 'Dinleme: {listen} dk • Yapay zekâ soruları: {ai}',
  labelEnabled: 'Etkin',
  labelWakeWord: 'Uyandırma kelimesi',
  labelDialect: 'Lehçe',
  labelPersonality: 'Komik kişilik',
  labelProtection: 'Koruma',
  labelWelcome: 'Karşılama',
  labelLanguage: 'Bot dili',
  yes: 'evet',
  no: 'hayır',
  on: 'açık',
  off: 'kapalı',
  dialectGulf: 'Körfez',
  dialectSyrian: 'Suriye',
  dialectEgyptian: 'Mısır',
  dialectMsa: 'Fasih Arapça',
  welcomeEnabledNote: '✅ Karşılama mesajları etkin.',
  welcomeDisabledNote: '⚠️ Karşılama mesajları şu an devre dışı — panelden veya /settings ile etkinleştir.',
  welcomeChannelNote: '📢 Karşılama kanalı: {channel}',
  welcomeNoChannelNote: '⚠️ Henüz karşılama kanalı seçilmedi — panelden bir kanal seç.',
  welcomeChannelMissing: '🚨 Ayarlanan karşılama kanalı artık yok ya da metin kanalı değil — yenisini seç.',
  welcomeChannelNoSend: '🚨 Botun karşılama kanalında mesaj gönderme izni yok — hiçbir karşılama mesajı ulaşmayacak!',
  welcomeChannelNoAttach: '⚠️ Botun karşılama kanalında dosya ekleme izni yok — metin, karşılama görseli olmadan ulaşacak.',
  defaultWelcome: 'Hoş geldin {user}, {server} sunucusuna! 🎮',
  defaultFarewell: 'Güle güle {user} 👋',
  unknownMember: '?',
  reasonWord: 'yasaklı kelime',
  reasonScam: 'dolandırıcılık',
  reasonInvite: 'yabancı davet bağlantısı',
  reasonShortener: 'bağlantı kısaltıcı',
  textDeleted: '{user} mesajın silindi ({reason}). Şüpheli bağlantılar/dolandırıcılık yasak.',
  textDeletedTimeout: '{user} mesajın silindi ({reason}) ve tekrar ettiğin için {minutes} dk susturuldun.',
  textLogDeleted: '🛡️ {channel} kanalında {user} adlı üyenin mesajı silindi — sebep: {reason}',
  textLogTimeoutSuffix: ' — ⏳ {minutes} dk susturma ({strike}. ihlal)',
  voiceWarnNotice: '⚠️ Uyarı {user}: diline dikkat et. Tekrarında ses kanalından çıkarılırsın.',
  voiceKickedNotice: '🚫 {user} uygunsuz sözler nedeniyle ses kanalından çıkarıldı.',
  voiceKickFailedNotice: '⚠️ {user} adlı üyeden uygunsuz sözler tespit edildi ama çıkarılamadı — bot rolünün üyeninkinden üstte olduğundan ve Üyeleri Taşı izninden emin ol.',
  summaryTitle: '📊 **Haftalık özet — {server}**',
  summaryTotals: '💬 Mesajlar: **{messages}** • 🎙️ Ses dakikaları: **{voiceMinutes}**',
  summaryTopHeader: 'Bu haftanın en aktifleri:',
  summaryTopLine: '{medal} {user} — {messages} mesaj, {voiceMinutes} dakika ses',
  // AI channel summary (catch me up)
  summaryEmpty: 'Bu kanalda özetlenecek yeterli mesaj yok.',
  summaryHeader: '📝 **Son mesajların özeti:**',
  // voice command responses (routed by bot language)
  voiceLeft: 'Ses kanalından çıktım.',
  voiceStopped: 'Dinlemeyi durdurdum.',
  voicePing: 'Gecikme {ms} ms.',
  voiceKicked: '{name} sesten atıldı.',
} as const satisfies Record<keyof typeof ar, string>;
